# Generated by Django 4.2.7 on 2024-01-06 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cars/media/uploads/'),
            preserve_default=False,
        ),
    ]
