# Generated by Django 4.2.7 on 2024-01-07 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_remove_car_image_car_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
